services:

    #----------------------------------------------------------------------------------------------
    # Admins
    #----------------------------------------------------------------------------------------------

    hi_sulu_blog.admin.admin:
        class: HiccupInsurance\SuluBlogBundle\Admin\BlogAdmin
        arguments:
            - "%sulu_admin.name%"
        tags:
            - { name: sulu.admin }